version: "3"

services:
  nginx:
    image: particle4dev/docker-nginx-boilerplate:latest
    container_name: nginx
    # command: tail -f /dev/null
    volumes:
      - ${PWD}/sites-enabled:/etc/nginx/sites-enabled:rw
      - ${PWD}/sites-available:/etc/nginx/sites-available:rw
      - ${PWD}/nginx-logs:/var/log/nginx
      - ${PWD}/nginx-cache:/tmp/nginx/cache
      - /etc/letsencrypt/live/news-pwa.particle4dev.com:/data/ssl
      - /etc/letsencrypt/archive:/archive
    ports:
      - "80:80"
      - "443:443"
  server:
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mongodb://mongo:27017/new-pwa
  mongo:
    image: mongo:3.2
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data
      - ${PWD}/../backup:/backup:rw
      - ${PWD}/../bin:/scripts:rw
